# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QInputDialog, QLineEdit, QFileDialog
from model import Perceptron
import numpy as np
import matplotlib.pyplot as plt


class Ui_MainWindow(object):
   

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(542, 584)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")



        self.initial_w1 = QtWidgets.QLineEdit(self.centralwidget)
        self.initial_w1.setGeometry(QtCore.QRect(40, 80, 71, 20))
        self.initial_w1.setObjectName("initial_w1")

        self.initial_w2 = QtWidgets.QLineEdit(self.centralwidget)
        self.initial_w2.setGeometry(QtCore.QRect(130, 80, 71, 20))
        self.initial_w2.setObjectName("initial_w2")
        
        self.initial_w3 = QtWidgets.QLineEdit(self.centralwidget)
        self.initial_w3.setGeometry(QtCore.QRect(220, 80, 71, 20))
        self.initial_w3.setObjectName("initial_w3")
        
        self.initial_w4 = QtWidgets.QLineEdit(self.centralwidget)
        self.initial_w4.setGeometry(QtCore.QRect(310, 80, 71, 20))
        self.initial_w4.setObjectName("initial_w4")
        
        self.initial_b = QtWidgets.QLineEdit(self.centralwidget)
        self.initial_b.setGeometry(QtCore.QRect(400, 80, 71, 20))
        self.initial_b.setObjectName("initial_b")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 60, 47, 13))
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 60, 47, 13))
        self.label_3.setObjectName("label_3")
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(230, 60, 47, 13))
        self.label_4.setObjectName("label_4")
        
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 60, 47, 13))
        self.label_5.setObjectName("label_5")
        
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(410, 60, 47, 13))
        self.label_6.setObjectName("label_6")
        
        self.fitButton = QtWidgets.QPushButton(self.centralwidget)
        self.fitButton.setGeometry(QtCore.QRect(120, 120, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.fitButton.setFont(font)
        self.fitButton.setObjectName("fitButton")
        
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 280, 47, 13))
        self.label_7.setObjectName("label_7")
        
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 260, 47, 13))
        self.label_8.setObjectName("label_8")
        
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 220, 47, 13))
        self.label_9.setObjectName("label_9")
        
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(40, 300, 47, 13))
        self.label_10.setObjectName("label_10")
        
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 240, 47, 13))
        self.label_11.setObjectName("label_11")
        
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 180, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(320, 180, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        
        self.label_18 = QtWidgets.QLabel(self.centralwidget)
        self.label_18.setGeometry(QtCore.QRect(370, 220, 61, 16))
        self.label_18.setObjectName("label_18")
        
        self.predictButton = QtWidgets.QPushButton(self.centralwidget)
        self.predictButton.setGeometry(QtCore.QRect(410, 400, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.predictButton.setFont(font)
        self.predictButton.setObjectName("predictButton")
        
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 340, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        
        self.input_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_3.setGeometry(QtCore.QRect(220, 410, 71, 20))
        self.input_3.setObjectName("input_3")
        
        self.input_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_2.setGeometry(QtCore.QRect(130, 410, 71, 20))
        self.input_2.setObjectName("input_2")
        
        self.input_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_1.setGeometry(QtCore.QRect(40, 410, 71, 20))
        self.input_1.setObjectName("input_1")
        
        self.input_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_4.setGeometry(QtCore.QRect(310, 410, 71, 20))
        self.input_4.setObjectName("input_4")
        
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(320, 390, 47, 13))
        self.label_15.setObjectName("label_15")
        
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(230, 390, 47, 13))
        self.label_16.setObjectName("label_16")
        
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(50, 390, 47, 13))
        self.label_17.setObjectName("label_17")
        
        self.label_20 = QtWidgets.QLabel(self.centralwidget)
        self.label_20.setGeometry(QtCore.QRect(140, 390, 47, 13))
        self.label_20.setObjectName("label_20")
        
        self.optimized_w3 = QtWidgets.QLabel(self.centralwidget)
        self.optimized_w3.setGeometry(QtCore.QRect(110, 260, 75, 13))
        self.optimized_w3.setText("")
        self.optimized_w3.setObjectName("optimized_w3")
        
        self.optimized_w4 = QtWidgets.QLabel(self.centralwidget)
        self.optimized_w4.setGeometry(QtCore.QRect(110, 280, 75, 13))
        self.optimized_w4.setText("")
        self.optimized_w4.setObjectName("optimized_w4")
        
        self.optimized_w1 = QtWidgets.QLabel(self.centralwidget)
        self.optimized_w1.setGeometry(QtCore.QRect(110, 220, 75, 13))
        self.optimized_w1.setText("")
        self.optimized_w1.setObjectName("optimized_w1")
        
        self.optimized_b = QtWidgets.QLabel(self.centralwidget)
        self.optimized_b.setGeometry(QtCore.QRect(110, 300, 75, 13))
        self.optimized_b.setText("")
        self.optimized_b.setObjectName("optimized_b")
        
        self.optimized_w2 = QtWidgets.QLabel(self.centralwidget)
        self.optimized_w2.setGeometry(QtCore.QRect(110, 240, 75, 13))
        self.optimized_w2.setText("")
        self.optimized_w2.setObjectName("optimized_w2")
        
        self.accurecy = QtWidgets.QLabel(self.centralwidget)
        self.accurecy.setGeometry(QtCore.QRect(450, 220, 65, 13))
        self.accurecy.setText("")
        self.accurecy.setObjectName("accurecy")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 542, 21))
        
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        
        self.menufile.setObjectName("menufile")
        self.menuedit = QtWidgets.QMenu(self.menubar)
        
        self.menuedit.setObjectName("menuedit")
        MainWindow.setMenuBar(self.menubar)
        
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        
        MainWindow.setStatusBar(self.statusbar)
        
        self.actionupload_file = QtWidgets.QAction(MainWindow)
        self.actionupload_file.setObjectName("actionupload_file")

        self.actionEnter_learningRate = QtWidgets.QAction(MainWindow)
        self.actionEnter_learningRate.setObjectName("actionEnter_learningRate")
        
        self.menuedit.addAction(self.actionEnter_learningRate)
        self.menufile.addAction(self.actionupload_file)

        
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuedit.menuAction())
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.category = QtWidgets.QLabel(self.centralwidget)
        self.category.setGeometry(QtCore.QRect(150, 500, 150, 13))
        self.category.setText("")
        self.category.setObjectName("category")
        
        self.category_lable = QtWidgets.QLabel(self.centralwidget)
        self.category_lable.setGeometry(QtCore.QRect(50, 500, 150, 13))
        self.category_lable.setText("Category: ")
        self.category_lable.setObjectName("category_lable")

        
###################################################################################################
        # Code that i added manually and not auto generated
        self.actionupload_file.triggered.connect(self.openFile)
        self.fitButton.clicked.connect(self.fitModel)
        self.predictButton.clicked.connect(self.predictOutput)

    def openFile(self):
        path = QFileDialog.getOpenFileName(None,'Open a file', './','text Files (*.txt*)')
        data = np.genfromtxt(path[0], delimiter=',')
        self.data = data
        return data

    
    def preProcess(self):
        num_of_features = len(self.data[0])-1
        X, y = self.data[:, :num_of_features], self.data[:, num_of_features]
        y = y.astype(np.int)
        shuffle_idx = np.arange(y.shape[0])
        shuffle_rng = np.random.RandomState(13)
        shuffle_rng.shuffle(shuffle_idx)
        X, y = X[shuffle_idx], y[shuffle_idx]

        X_train, X_test = X[shuffle_idx[:1000]], X[shuffle_idx[1000:]]
        y_train, y_test = y[shuffle_idx[:1000]], y[shuffle_idx[1000:]]
        mu, sigma = X_train.mean(axis=0), X_train.std(axis=0)
        X_train = (X_train - mu) / sigma
        X_test = (X_test - mu) / sigma
        X_train.std(axis=0)
        
        self. X_train = X_train
        self. y_train = y_train
        self. X_test = X_test
        self. y_test = y_test
        return X_train, y_train, X_test, y_test
    
    def setInitialParameters(self):
        self.w1 = float(self.initial_w1.text())
        self.w2 = float(self.initial_w2.text())
        self.w3 = float(self.initial_w3.text())
        self.w4 = float(self.initial_w4.text())
        self.weights = np.array([[self.w1],[self.w2],[self.w3],[self.w4]], dtype=np.float)
        self.b = float(self.initial_b.text())
        self.bias = np.array([self.b],  dtype=np.float)

    def fitModel(self):
        self.preProcess()
        self.setInitialParameters()
        ppn = Perceptron(4, 0.01, self.weights, self.bias)
        ppn.train(self.X_train, self.y_train, epochs=10)
        print('Model parameters:\n\n')
        print('  Weights: %s\n' % ppn.weights)
        print('  Bias: %s\n' % ppn.bias)
        train_acc = ppn.evaluate(self.X_train, self.y_train)
        print('Train set accuracy: %.2f%%' % (train_acc*100))
        test_acc = ppn.evaluate(self.X_test, self.y_test)
        print('Test set accuracy: %.2f%%' % (test_acc*100))
        self.weights = ppn.weights
        self.bias = ppn.bias
        self.optimized_w1.setText(str(round(self.weights[0][0], 6)))
        self.optimized_w2.setText(str(round(self.weights[1][0], 6)))
        self.optimized_w3.setText(str(round(self.weights[2][0], 6)))
        self.optimized_w4.setText(str(round(self.weights[3][0], 6)))
        self.optimized_b.setText(str(round(self.bias[0], 6)))
        self.accurecy.setText(str(round(test_acc*100,2)))
    
    def predictOutput(self):
        self.x1 = float(self.input_1.text())
        self.x2 = float(self.input_2.text())
        self.x3 = float(self.input_3.text())
        self.x4 = float(self.input_4.text())
        self.x = np.array([self.x1,self.x2,self.x3, self.x4], dtype=np.float)
        ppn = Perceptron(4, 0.01, self.weights, self.bias)  
        output = ppn.forward(self.x)
        self.category.setText(str(output[0])) 



###################################################################################################

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Enter initial parameters:"))
        self.label_2.setText(_translate("MainWindow", "w1"))
        self.label_3.setText(_translate("MainWindow", "w2"))
        self.label_4.setText(_translate("MainWindow", "w3"))
        self.label_5.setText(_translate("MainWindow", "w4"))
        self.label_6.setText(_translate("MainWindow", "b"))
        self.fitButton.setText(_translate("MainWindow", "Fit model and show optimized parameters"))
        self.label_7.setText(_translate("MainWindow", "w4:"))
        self.label_8.setText(_translate("MainWindow", "w3:"))
        self.label_9.setText(_translate("MainWindow", "w1:"))
        self.label_10.setText(_translate("MainWindow", "b:"))
        self.label_11.setText(_translate("MainWindow", "w2:"))
        self.label_12.setText(_translate("MainWindow", "Optimized parameters:"))
        self.label_13.setText(_translate("MainWindow", "Model Info:"))
        self.label_18.setText(_translate("MainWindow", "Accurecy:"))
        self.predictButton.setText(_translate("MainWindow", "test"))
        self.label_14.setText(_translate("MainWindow", "Enter your own data record and test the output:"))
        self.label_15.setText(_translate("MainWindow", "x4"))
        self.label_16.setText(_translate("MainWindow", "x3"))
        self.label_17.setText(_translate("MainWindow", "x1"))
        self.label_20.setText(_translate("MainWindow", "x2"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuedit.setTitle(_translate("MainWindow", "edit"))
        self.actionupload_file.setText(_translate("MainWindow", "upload data file"))
        self.actionEnter_learningRate.setText(_translate("MainWindow", "adjust the learning rate"))

    



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
